version: '3'

services:
  transactional:
    image: postgres:12
    environment:
      POSTGRES_DB: dvdrental
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./data/dvdrental.sql:/docker-entrypoint-initdb.d/dvdrental.sql
      - postgres:/shared_directory

  analytics:
    image: postgres:12
    environment:
      POSTGRES_DB: analytics
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5433:5432
    volumes:
      - postgres:/shared_directory

  extract-load:
    build:
      context: .
      dockerfile: Dockerfile.extract_load
    ports:
      - 5435:5432
    volumes:
      - postgres:/shared_directory
    depends_on:
      - transactional
      - analytics  

volumes:
  postgres: